[versions]
dependency_analysis = "3.5.1"
detekt = "1.23.8"
gradle_versions_filter = "0.1.16"
graal = "0.11.3"
guava = "33.5.0-jre"
kotlin = "2.3.0"
kotlinter = "5.3.0"

[libraries]
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

[plugins]
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency_analysis" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
graal = { id = "org.graalvm.buildtools.native", version.ref = "graal" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
versions = { id = "se.ascp.gradle.gradle-versions-filter", version.ref = "gradle_versions_filter" }
